version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/static:/www/data/images

    depends_on:
      - apache
      - freshrss

  apache:
    image: php:8.3-apache
    container_name: apache
    volumes:
      - ./apache/htdocs:/var/www/html
      - ./apache/php:/usr/local/etc/php
    environment:
      PHP_ERROR_REPORTING: 'E_ALL & ~E_DEPRECATED & ~E_STRICT'
      PHP_MEMORY_LIMIT: 256M
      PHP_MAX_UPLOAD: 50M
      PHP_MAX_EXECUTION_TIME: 30
    expose:
      - "80"

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
    environment:
      - CRON_MIN=*/20
      - TZ=Europe/Paris
    expose:
      - "80"

volumes:
  freshrss_data: